import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
    id 'org.jetbrains.kotlin.jvm' version '1.9.23'
}

group = 'io.tpalucki'
version = '0.0.2-SNAPSHOT'

java {
    sourceCompatibility = '21'
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.jetbrains.kotlin:kotlin-reflect'
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.8.1"
}

tasks.withType(KotlinCompile)
        .configureEach {
            kotlinOptions {
                freeCompilerArgs += '-Xjsr305=strict'
                jvmTarget = '21'
            }
        }

tasks.named('test') {
    useJUnitPlatform()
}
