plugins {
    id 'org.jetbrains.kotlin.jvm' version '2.4.20-Beta2'
}

group = 'io.tpalucki'
version = '0.0.2-SNAPSHOT'

java {
    sourceCompatibility = '25'
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.jetbrains.kotlin:kotlin-reflect'
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.11.0"
}

tasks.named('test') {
    useJUnitPlatform()
}
